@startuml

database FileStorage {
    [External]
    [Storage]
}

cloud MQTT {
}

node ML {
    frame Plugins {
        [faces]
        [similarity]
    }
    Plugins <-- [TensorFlow]
    Plugins <-- FileStorage
}

node Backend {
    frame Scrapper {
        [File Info]
        [Exif]
        [Sidecar]
    }
    frame Transcoder {
        [ImageMagic]
        [ffmpeg]
    }
    frame DB {
        [MariaDB]
    }

    Scrapper --> FileStorage
    Transcoder --> FileStorage
}

node Svelte {
    [Svelte Client] --> [Svelte Server]

    [Svelte Server] <-- FileStorage
    [Svelte Server] <--> Backend
    [Svelte Server] <--> MQTT
}

Backend --> ML
ML <--> MQTT
Backend <--> MQTT


@enduml
