@startuml Item Flow

actor "Client" as Client
queue "MQTT" as MQTT
participant "ML" as ML
database "DB" as DB
control "Gorm" as Gorm #LightCoral

box "Gontroller"
collections "Chain" as Chain #LightSeaGreen

control "FsWalker" as Watcher
queue "FileDto\nchannel" as FilesCh #LightGreen

control "MetaProcessor" as EXIF

queue "ItemDto\nChannel" as InfoCh #LightGreen

control "Photo\nProcessor" as PhotoProcessor
control "Video\nProcessor" as VideoProcessor
queue "Items\nchannel" as ItemsCh #LightGreen
end box

== Gontroller ==
Chain -> Chain: Startup
activate Chain #LightSeaGreen
Chain -> Watcher: Run
deactivate Chain

activate Watcher #LightSeaGreen
loop #LightGreen
    Watcher -> FilesCh: There is changes\np := path\ng := NewGuid()
    deactivate Watcher
    activate FilesCh #LightSeaGreen
    
end

loop #LightGreen Files channel subscribe 
    FilesCh -> EXIF: p -> path\ng -> NewGuid()
    deactivate FilesCh #LightSeaGreen
    activate EXIF #LightSeaGreen
    EXIF -> ExifCh: p, g,\nImageSize,\nImageWidth,\nMIMEType
    deactivate EXIF
    activate ExifCh #LightSeaGreen
end

loop#LightCyan Validating Loop
    ExifCh -> Preprocessor: p, g,\nImageSize,\nImageWidth,\nMIMEType
    deactivate ExifCh
    activate Preprocessor #LightBlue
    activate Preprocessor #Orange
    
    Preprocessor -> Preprocessor: Check Mimetype
    
    alt MimeType == */*
        Preprocessor ->x Gorm: Save as Known Unwanted
        activate Gorm

        
    else MimeType == image/* || video/*
        Preprocessor -> InfoCh: 
        destroy Preprocessor
        activate InfoCh #Orange
        Preprocessor -> Gorm: Check if it is new/changed/known
        deactivate Preprocessor
    end

    alt known
        Gorm -> Preprocessor: known and same hash
        activate Preprocessor
        Preprocessor ->x Preprocessor: Ignore
        deactivate Preprocessor

    else new
        Gorm -> Preprocessor: new
        activate Preprocessor
        Preprocessor -> Chain: New Item
        deactivate Preprocessor
        activate Chain
        Chain -> InfoCh: New Item
        activate InfoCh
        Chain -->> MQTT: New Item
        deactivate Chain
        activate MQTT

    else changed
        Gorm -> Preprocessor: known but different hash
        deactivate Gorm
        activate Preprocessor
        Preprocessor -> Chain: Change guid to known\nUpdate Item
        deactivate Preprocessor
        activate Chain
        Chain -> InfoCh: Updated Item
        Chain -->> MQTT: Updated Item
        deactivate Chain

    end
end

group #LightYellow Photo
    InfoCh -> PhotoProcessor: image/*
    activate PhotoProcessor
    PhotoProcessor -> ItemsCh: scaled photo
    deactivate PhotoProcessor
    activate ItemsCh
end
group #LightYellow Video
    InfoCh -> VideoProcessor: video/*
    deactivate InfoCh
    deactivate InfoCh
    activate VideoProcessor
    VideoProcessor -> ItemsCh: scaled video
    deactivate VideoProcessor
end

ItemsCh -> Chain: Processed Item
deactivate ItemsCh
activate Chain
Chain -->> MQTT: Processed Item
deactivate Chain
deactivate MQTT


== Async Ops ==
group New Item
    Chain -->> MQTT: New Item
    activate MQTT
    activate Chain
    MQTT -->> Client: New Item
    activate Client
    Client -> Client: Draw Preloader\nCheck Size\nFix Grid Layout
end

group Updated Item
    Chain -->> MQTT: Updated Item
    MQTT -->> Client: Updated Item
    Client -> Client: Check Size\nFix Grid Layout
end

group Processed Item
    Chain -->> MQTT: Processed Item
    deactivate Chain
    MQTT -->> ML: Processed Item
    activate ML

    MQTT -->> Client: Processed Item
    deactivate MQTT
    Client -> Client: Draw Thumb\nEnable View Screen
    deactivate Client
end


== goMLer ==
autonumber
ML <- ML: Faces
ML <- ML: Objects
ML <- ML: Plugin #3
ML <- ML: Plugin #4
ML <- ML: Plugin #5
ML -->> MQTT: ML Done
deactivate ML
activate MQTT
autonumber stop

group ML Results
MQTT -->> Gorm: New ML Metadata
MQTT -->> Client: Show ML results
deactivate MQTT

end

@enduml
