@startuml ML Flow

queue "MQTT" as MQTT

participant "Server" as Server

participant "ML" as ML
control "ML\nPlugin" as MLPlugin

== goMLer ==

MQTT -->> ML: Processed Item
activate MQTT
deactivate MQTT
activate ML#LightGreen


loop Foreach Plugin
ML -> MLPlugin: Data
activate MLPlugin
MLPlugin -> ML: Meta
deactivate MLPlugin
ML -->> MQTT: Meta
deactivate ML
activate MQTT
end

MQTT -->> Server: New ML Metadata
deactivate MQTT
activate Server
Server -> DB: Update Metadata
deactivate Server

@enduml
