@startuml Walker and validating

control fp.Walk
collections fileCh

control exifreader #LightCoral
collections exifCh #LightCoral

box GateKeeper #LightSkyBlue
control validator
control gorm
control decorator
end box
collections itemCh


activate fp.Walk
note over fp.Walk, fileCh #LightGreen
Make group of files by name <b>[]FileEntry,
First element is main file, others sidecars
Sends only new/changed
end note
fp.Walk -> fileCh: new group
deactivate fp.Walk
activate fileCh
fileCh -> exifreader: new group
deactivate fileCh
activate exifreader #LightCoral
exifreader -> exifCh: exif...
note over fileCh, exifCh #LightCoral
As soon as it takes list of files
Better to merge exifreader with validator
To be able to check whole group in a row
end note
deactivate exifreader
activate exifCh #LightCoral
exifCh -> validator: exif...
deactivate exifCh
activate validator

validator -> gorm: hash(path,\nexif...\nbytesize)
deactivate validator
activate gorm

alt found the same
    note over validator, gorm: same path and same hash\ndo nothing
    gorm ->x validator: <font color=red><b>nil

else found moved
    note over validator, gorm
    same hash, different path,
    old path <b><font color=red>not exists
    end note
    gorm <- gorm: update path
    gorm ->x validator: <font color=red><b>nil

else don't found
    note over validator, gorm
    path and hash not found
    create new item
    end note
    note over validator, gorm
    same hash, different path,
    old path <b><font color=red>also exists
    create new one (duplicate)
    end note
    gorm <- gorm: create
    gorm -> validator: <font color=green><b>new guid
    activate validator

else found changed
    note over validator, gorm
    same path, different hash
    <b>have to regenerate thumbs
    end note
    gorm -> validator: <font color=blue><b>existing guid
    deactivate gorm

end

validator -> decorator: guid, exif...
deactivate validator
activate decorator
decorator -> itemCh: exif{} 
deactivate decorator

@enduml