@startuml Client Flow

actor "Client" as Client
queue "MQTT" as MQTT

participant "Server" as Server
control "Broadcast" as Broadcast

control "FS Watcher" as Watcher
queue "Files\nchannel" as FilesCh #LightGreen

control "Exif extractor" as EXIF
queue "EXIF\nChannel" as ExifCh #LightGreen

control "Preprocess" as Preprocessor

queue "Infos\nChannel" as InfoCh #LightGreen

control "Photo\nProcessor" as PhotoProcessor
control "Video\nProcessor" as VideoProcessor
queue "Items\nchannel" as ItemsCh #LightGreen

database "DB" as DB
participant "ML" as ML

== Gontroller ==
activate Server
activate MQTT
Server -> Server: Startup
Server -> Watcher: Run

activate Watcher
loop #LightGray
    Watcher --> Watcher: Wait FS event
    Watcher -> FilesCh: There is changes\np := path\ng := NewGuid()
    deactivate Watcher
    activate FilesCh
    
end

loop #LightGreen Files channel subscribe 
    FilesCh -> EXIF: p -> path\ng -> NewGuid()
    deactivate FilesCh
    activate EXIF
    EXIF -> ExifCh: p, g,\nImageSize,\nImageWidth,\nMIMEType
    deactivate EXIF
    activate ExifCh
end

loop
    ExifCh -> Preprocessor: p, g,\nImageSize,\nImageWidth,\nMIMEType
    deactivate ExifCh
    activate Preprocessor
    
    Preprocessor -> Preprocessor: Check Mimetype
    
    alt MimeType == image/* || video/*
        Preprocessor -> DB: Check if it is new/changed/known
        activate DB

        
    else MimeType == */*
        Preprocessor ->x Preprocessor: Ignore
        deactivate Preprocessor
    end

    alt known
        DB -> Preprocessor: known and same hash
        activate Preprocessor
        Preprocessor ->x Preprocessor: Ignore
        deactivate Preprocessor

    else new
        DB -> Preprocessor: new
        activate Preprocessor
        Preprocessor -> Broadcast: New Item
        deactivate Preprocessor
        activate Broadcast
        Broadcast -> InfoCh: New Item
        activate InfoCh
        Broadcast -> Server: New Item
        deactivate Broadcast

    else changed
        DB -> Preprocessor: known but different hash
        deactivate DB
        activate Preprocessor
        Preprocessor -> Broadcast: Change guid to known\nUpdate Item
        deactivate Preprocessor
        activate Broadcast
        Broadcast -> InfoCh: Updated Item
        Broadcast -> Server: Updated Item
        deactivate Broadcast

    end
end

        group Photo
            InfoCh -> PhotoProcessor: image/*
            activate PhotoProcessor
            PhotoProcessor -> ItemsCh: scaled photo
            deactivate PhotoProcessor
            activate ItemsCh
        end
        group Video
            InfoCh -> VideoProcessor: video/*
            deactivate InfoCh
            activate VideoProcessor
            VideoProcessor -> ItemsCh: scaled video
            deactivate VideoProcessor
        end

ItemsCh -> Broadcast: Processed Item
deactivate ItemsCh
activate Broadcast
Broadcast -> Server: Processed Item
deactivate Broadcast

== Async Ops ==
group New Item
    Server -->> MQTT: New Item
    MQTT -->> Client: New Item
    activate Client
    Client -> Client: Draw Preloader\nCheck Size\nFix Grid Layout
end

group Updated Item
    Server -->> MQTT: Updated Item
    MQTT -->> Client: Updated Item
    Client -> Client: Check Size\nFix Grid Layout
end

group Processed Item
    Server -->> MQTT: Processed Item
    MQTT -->> ML: Processed Item
    activate ML

    MQTT -->> Client: Processed Item
    Client -> Client: Draw Thumb\nEnable View Screen
    deactivate Client
end


== goMLer ==
autonumber
ML <- ML: Faces
ML <- ML: Objects
ML <- ML: Plugin #3
ML <- ML: Plugin #4
ML <- ML: Plugin #5
ML -> MQTT: ML Done
deactivate ML
autonumber stop

group ML Results
MQTT -> Server: New ML Metadata
Server -> DB: Update Metadata
MQTT -> Client: Show ML results
end

@enduml
