@startuml Item Flow

!pragma teoz true
actor "Client" as Client
queue "MQTT" as MQTT
participant "ML" as ML

box gontroller
database "DB" as DB
control "Gorm" as Gorm

collections "Chain" as Chain #LightSeaGreen

box fswalker #LightCyan
control "FsWalker" as Watcher
queue "FileDto\nchannel" as FilesCh #LightGreen
end box

box metaprocessor #LightCyan
control "MetaProcessor" as EXIF
queue "ItemDto\nChannel" as InfoCh #LightGreen
end box

box transcoder #LightCyan
control "Photo\nProcessor" as PhotoProcessor
control "Video\nProcessor" as VideoProcessor
collections "FS" as ItemsCh #LightGreen
end box

end box

== Gontroller ==
Chain -> Chain: Startup
activate Chain
Chain -> Watcher: Run
deactivate Chain

activate Watcher
loop #LightGreen
    Watcher <- Watcher: New file
    alt Same Base Name As Current Group?
    Watcher <- Watcher: Append\nto group?
    else Different Base Name
    Watcher <- Watcher: Close group?
    Watcher -> Gorm: Check\nmodeTime/size/guid\nknown/added/modified
    activate Gorm
    Gorm -> Watcher: New Guid if unknown
    deactivate Gorm
    end
    Watcher -> FilesCh: Changed\n[]FileDto
    deactivate Watcher
    activate FilesCh
    
end

loop #LightGreen Files channel subscribe 
    FilesCh -> EXIF: []FileDto
    deactivate FilesCh
    activate EXIF
    EXIF <- EXIF: RawExif
    EXIF -> Gorm: Check Guid/Hash/Path
    activate Gorm
    Gorm -> EXIF: ItemFromFile(FileDto) for unknown
    deactivate Gorm
    EXIF <- EXIF: Update Meta
    EXIF <- EXIF: Update ItemState
    EXIF -> InfoCh: changed ItemDto\nOne main Item\nmerged from all sidecars
    deactivate EXIF
    activate InfoCh
end

group #LightYellow Photo
    InfoCh -> PhotoProcessor: image/*
    activate PhotoProcessor
    PhotoProcessor -> ItemsCh: scaled photo
    deactivate PhotoProcessor
    activate ItemsCh
end
group #LightYellow Video
    InfoCh -> VideoProcessor: video/*
    deactivate InfoCh
    activate VideoProcessor
    VideoProcessor -> ItemsCh: scaled video
    deactivate VideoProcessor
end

ItemsCh -> Chain: Processed Item
deactivate ItemsCh
activate Chain
Chain -->> MQTT: Processed Item
deactivate Chain
deactivate MQTT


== Async Ops ==
group New Item
    Chain -->> MQTT: New Item
    activate MQTT
    activate Chain
    MQTT -->> Client: New Item
    activate Client
    Client -> Client: Draw Preloader\nCheck Size\nFix Grid Layout
end

group Updated Item
    Chain -->> MQTT: Updated Item
    MQTT -->> Client: Updated Item
    Client -> Client: Check Size\nFix Grid Layout
end

group Processed Item
    Chain -->> MQTT: Processed Item
    deactivate Chain
    MQTT -->> ML: Processed Item
    activate ML

    MQTT -->> Client: Processed Item
    deactivate MQTT
    Client -> Client: Draw Thumb\nEnable View Screen
    deactivate Client
end


== goMLer ==
autonumber
ML <- ML: Faces
ML <- ML: Objects
ML <- ML: Plugin #3
ML <- ML: Plugin #4
ML <- ML: Plugin #5
ML -->> MQTT: ML Done
deactivate ML
activate MQTT
autonumber stop

group ML Results
MQTT -->> Gorm: New ML Metadata
MQTT -->> Client: Show ML results
deactivate MQTT

end

@enduml
