@startuml
'https://plantuml.com/sequence-diagram

box Gontroller #LightBlue
collections SQL
control GO
end box

box Svebapp #LightGreen
control SVBack
control SVFront
collections Dexie
control View
end box

note over SQL
- Guid
- HashShort
- MimeType
- State
- Date
- Path
- Size
- Ratio
end note
SQL -> GO:

note over GO
- Guid
- MimeType
- Date
- Ratio
end note
GO -> SVBack:

note over SVBack
- Guid
- MimeType
- Date
- Ratio
end note
SVBack -> SVFront:

note over SVFront
- Guid
- MimeType
- Date
- Ratio
end note
SVFront -> Dexie:

note over Dexie
- Guid
- index (position in list)
- MimeType
- Ratio
end note
Dexie -> View:

@enduml
